export interface IMainMenuResponse {
  ID: number;
  post_author: number;
  post_date: string;
  post_date_gmt: string;
  post_content: string;
  post_title: string;
  post_excerpt: string;
  post_status: string;
  comment_status: string;
  ping_status: string;
  post_password: string;
  post_name: string;
  to_ping: string;
  pinged: string;
  post_modified: string;
  post_modified_gmt: string;
  post_content_filtered: string;
  post_parent: number;
  guid: string;
  menu_order: number;
  post_type: string;
  post_mime_type: string;
  comment_count: number;
  filter: string;
  db_id: number;
  menu_item_parent: number;
  object_id: number;
  object: string;
  type: string;
  type_label: string;
  url: string;
  title: string;
  target: string;
  attr_title: string;
  description: string;
  classes: string[];
  xfn: string;
  slug: string;
}

export interface ITechnologyStackResponse {
  id: number;
  date: string;
  date_gmt: string;
  guid: object;
  modified: string;
  modified_gmt: string;
  slug: string;
  status: string;
  type: string;
  link: string;
  title: object;
  author: number;
  comment_status: string;
  ping_status: string;
  template: string;
  meta: string[];
  description: object;
  caption: object;
  alt_text: string;
  media_type: string;
  mime_type: string;
  media_details: {
    width: number;
    height: number;
    file: string;
    sizes: object;
    image_meta: object;
  }
  post: number;
  source_url: string;
  _links: object;
}
